package main;

public class Settings {
	public static final String separator = ";";			// in the text file
	public static final int toGenerate = 20;			// number of partecipants generated by FakeGenerator
	public static final String filename = "data.txt";	// filename for reading from
}
